# ------------------------------------------------


### GET User by ID (200 OK)
GET http://localhost:3000/api/user/1


### GET User by ID (400 Bad Request)
GET http://localhost:3000/api/user/


### GET User by ID (404 Not Found)
GET http://localhost:3000/api/user/999


# ------------------------------------------------

### GET List of Gifs (200 OK)

GET  http://localhost:3000/api/search/dragon?pos=CBQQj5O069a4iAMaHgoKAD-_xHrzZGiiuBIQ13oCKGpr_iLYBRHtAAAAADAU


### GET List of Gifs (400 Bad Request)

GET  http://localhost:3000/api/search/

# ------------------------------------------------

### POST Upload Gif (200 OK)
POST http://localhost:3000/api/upload/
Content-Type: application/json

{
  "alt": "pepe",
  "images": { "gif": "https://media.giphy.com/media/3o7TKz9bX9v9KzCnXK/giphy.gif" },
  "description": "My Gif Description",
  "title": "My Gif",
  "tags": ["tag1", "tag2"],
  "id": "giffy-00001",
  "autor": "frieren"
}

# ------------------------------------------------

### LOGIN FRIEREN
POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
  "username": "Goku",
  "password": "4321"
}
 